django教程/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from  polls.models import Question

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap



from login import views as loginview

sitemaps = {
    'polls': GenericSitemap({'queryset': Question.objects.all(), 'question_text': 'pub_date'}, priority=0.6),
    # 如果还要加其它的可以模仿上面的
}
urlpatterns = [
    re_path(r'^admin/doc/',include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('login/', loginview.login,name='login'),
    path('register/', loginview.register,name='register'),
    path('logout/', loginview.logout,name='logout'),
    path('polls/', include('polls.urls')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),


    re_path(r'^captcha', include('captcha.urls'))
]

polls/urls.py
from django.contrib import admin
from django.urls import path,re_path
from  . import views
from polls.feed import LatestEntriesFeed
app_name = 'polls'
urlpatterns = [

    path('', views.index,name='index'),

    path('feed/', LatestEntriesFeed()),
    path('test/', views.test,name='test'),
    path('upload/', views.upload_file,name='upload_file'),
    re_path(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    re_path(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    re_path(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),




]

polls/models.py
import datetime
from django.db import models
from django.utils import  timezone
# Create your models here.
from  django.urls import  reverse
class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now



    #更换样式
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def get_absolute_url(self):
        return reverse('polls:detail', kwargs={'question_id': self.pk})


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/forms.py
from  django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import  loader
from django.urls import  reverse
from django.http import QueryDict
from polls.forms import UploadFileForm

import time
import django.dispatch
from django.dispatch import receiver

from django.views.decorators.cache import cache_page


import logging
# 获取一个logger对象
logger = logging.getLogger(__name__)
# Create your views here.

# 定义一个信号
work_done = django.dispatch.Signal(providing_args=['path', 'time'])


from polls.models import Question, Choice
# Create your views here.

#因为使用了视图缓存，所以下面方法只是用一次
# @cache_page(60 * 15)
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    templates=loader.get_template('polls/index.html')

    context = {
        'latest_question_list': latest_question_list,
    }
    # request.session['fav'] = 'blue'
    # print(request.session.get('fav', 'red'))
    # print(request.session['fav'])
    #两种方式
    # return HttpResponse(templates.render(context, request))

   #测试logging
    logging.info('Something went wrong!')

   #测试信号接受
    # 发送信号，将请求的IP地址和时间一并传递过去
    url_path = request.path
    work_done.send(index, path=url_path, time=time.strftime("%Y-%m-%d %H:%M:%S"))


    return render(request,'polls/index.html',context)

@receiver(work_done, sender=index)
def my_callback(sender, **kwargs):
    print("我在%s时间收到来自%s的信号，请求url为%s" % (kwargs['time'], sender, kwargs["path"]))

def detail(request, question_id):
    # try:
    #     question=Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise  Http404("Question does not exist")
    question=get_object_or_404(Question,pk=question_id)
    return render(request,"polls/detail.html" ,{"question":question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 发生choice未找到异常时，重新返回表单页面，并给出提示信息
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # 成功处理数据后，自动跳转到结果页面，防止用户连续多次提交。
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

from django.core import serializers
from django.contrib import messages
from django.core.mail import send_mail
def test(requset):

    #序列化
    data = serializers.serialize("xml", Choice.objects.all())
    print(data)

    #反序列
    # for obj in serializers.deserialize("xml", data):
    #  print(obj)
    #消息框架
    messages.add_message(requset,messages.INFO, 'Hello world.')


    # 发送邮件。

    send_mail( '来自龙之介的测试邮件',
        '分享一切！',
        'ken626014896@163.com',
        ['626014896@qq.com'],)
    print("发送信息到邮箱。。。。。。。")
    return render(requset,"polls/test.html")




#文件上传
def upload_file(request):
    if request.method == 'GET':

        return render(request, 'polls/upload.html')

    elif request.method=='POST':
        files=request.FILES.get('files')
        handle_uploaded_file(files,files.name)
        return HttpResponseRedirect(reverse('polls:index'))



#文件处理方法
def handle_uploaded_file(f,name):
    with open(name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="margin: 15% 40%;">
        <h1>欢迎登录！</h1>
       <form action="/login/" method="post">
            {% if message %}
            <div class="alert alert-warning">{{ message }}</div>
            {% endif %}

           {% csrf_token %}
            <p>
                <label for="id_username">用户名：</label>
                <input type="text" id="id_username" name="username" placeholder="用户名" autofocus required />
            </p>
            <p>
                <label for="id_password">密码：</label>
                <input type="password" id="id_password" placeholder="密码" name="password" required >
            </p>
            <input type="submit" value="确定">
        </form>
    </div>
</body>
</html>

login/templates/login/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>


{% if request.session.is_login %}
    <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
    <li><a href="{% url 'logout' %}">登出</a></li>
{% else %}

<a href="{% url  'login' %}" >登录</a>
<a href="{% url  'register' %}">注册</a>
{% endif %}




{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>

polls/templates/polls/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'polls:upload_file'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="user" />
    <input type="file" name="files" />
    <input type="submit" value="Submit" />
</form>
</body>
</html>